/**
 * OTA Update Controller
 * Simple file-based OTA serving for expo-updates.
 *
 * Bundle folder structure:
 *   Backend/ota-bundles/<apkVersion>/<otaVersion>/
 *     metadata.json   (generated by `npx expo export`)
 *     _expo/static/js/android/...hbc
 *     assets/...
 *
 * version.json tracks the latest OTA per APK version:
 *   "ota": { "1.0.18": { "currentOtaVersion": 1, "description": "..." } }
 */

import fs from "fs";
import path from "path";
import crypto from "crypto";

const OTA_DIR = path.join(process.cwd(), "ota-bundles");

function hashFileBase64(filePath) {
  const data = fs.readFileSync(filePath);
  return crypto.createHash("sha256").update(data).digest("base64url");
}

/**
 * Deterministic UUID v5 from a string (using a fixed namespace).
 * expo-updates requires the manifest `id` to be a valid UUID.
 */
function deterministicUUID(input) {
  const hash = crypto.createHash("sha256").update(input).digest("hex");
  // Format as UUID v4 shape: xxxxxxxx-xxxx-4xxx-Nxxx-xxxxxxxxxxxx
  return [
    hash.slice(0, 8),
    hash.slice(8, 12),
    "4" + hash.slice(13, 16),
    ((parseInt(hash.slice(16, 18), 16) & 0x3f) | 0x80)
      .toString(16)
      .padStart(2, "0") + hash.slice(18, 20),
    hash.slice(20, 32),
  ].join("-");
}

/**
 * GET /api/ota/check
 * Client sends: ?apkVersion=1.0.18&otaVersion=0
 * Returns: { updateAvailable, latestOta, description }
 */
export const checkOta = (req, res) => {
  try {
    const { apkVersion, otaVersion } = req.query;
    if (!apkVersion) {
      return res.json({ updateAvailable: false, reason: "missing apkVersion" });
    }

    const versionPath = path.join(process.cwd(), "version.json");
    const versionData = JSON.parse(fs.readFileSync(versionPath, "utf8"));
    const otaInfo = versionData.ota?.[apkVersion];

    if (!otaInfo || otaInfo.currentOtaVersion <= 0) {
      return res.json({ updateAvailable: false, reason: "no OTA for this APK" });
    }

    const clientOta = parseInt(otaVersion || "0", 10);
    if (clientOta >= otaInfo.currentOtaVersion) {
      return res.json({ updateAvailable: false, reason: "already up to date" });
    }

    return res.json({
      updateAvailable: true,
      latestOta: otaInfo.currentOtaVersion,
      description: otaInfo.description || "Update available",
    });
  } catch (err) {
    console.error("OTA check error:", err);
    res.status(500).json({ updateAvailable: false, error: err.message });
  }
};

/**
 * GET /api/ota/manifest
 * Expo Updates protocol endpoint.
 * expo-updates sends headers: expo-platform, expo-runtime-version, expo-current-update-id
 * Query: ?apkVersion=1.0.18
 */
export const getManifest = (req, res) => {
  try {
    const platform = req.headers["expo-platform"] || "android";
    const runtimeVersion = req.headers["expo-runtime-version"];
    const currentUpdateId = req.headers["expo-current-update-id"];
    const protocolVersion = req.headers["expo-protocol-version"] || "0";
    const apkVersion = req.query.apkVersion || runtimeVersion;

    console.log(`[OTA] manifest request: platform=${platform} runtime=${runtimeVersion} current=${currentUpdateId} proto=${protocolVersion}`);

    if (!apkVersion) {
      return sendNoUpdate(res, protocolVersion);
    }

    const versionPath = path.join(process.cwd(), "version.json");
    const versionData = JSON.parse(fs.readFileSync(versionPath, "utf8"));
    const otaInfo = versionData.ota?.[apkVersion];

    if (!otaInfo || otaInfo.currentOtaVersion <= 0) {
      return sendNoUpdate(res, protocolVersion);
    }

    const otaVersion = otaInfo.currentOtaVersion;
    const bundleDir = path.join(OTA_DIR, apkVersion, String(otaVersion));

    if (!fs.existsSync(bundleDir)) {
      console.error(`[OTA] Bundle dir not found: ${bundleDir}`);
      return sendNoUpdate(res, protocolVersion);
    }

    const metadataPath = path.join(bundleDir, "metadata.json");
    if (!fs.existsSync(metadataPath)) {
      console.error(`[OTA] metadata.json not found in ${bundleDir}`);
      return sendNoUpdate(res, protocolVersion);
    }

    const metadata = JSON.parse(fs.readFileSync(metadataPath, "utf8"));
    const platformMeta = metadata.fileMetadata?.[platform];
    if (!platformMeta) {
      console.error(`[OTA] No fileMetadata for platform: ${platform}`);
      return sendNoUpdate(res, protocolVersion);
    }

    // Deterministic UUID based on version string
    const updateId = deterministicUUID(`${apkVersion}_ota_${otaVersion}`);

    if (currentUpdateId && currentUpdateId === updateId) {
      console.log("[OTA] Client already has this update");
      return sendNoUpdate(res, protocolVersion);
    }

    const bundlePath = path.join(bundleDir, platformMeta.bundle);
    if (!fs.existsSync(bundlePath)) {
      console.error(`[OTA] Bundle file not found: ${bundlePath}`);
      return sendNoUpdate(res, protocolVersion);
    }

    const bundleHash = hashFileBase64(bundlePath);

    // Use the metadata.json file's mtime as a stable createdAt
    const metadataStat = fs.statSync(metadataPath);
    const createdAt = metadataStat.mtime.toISOString();

    // Build server URL from request
    const serverUrl = `${req.protocol}://${req.get("host")}`;

    const assets = (platformMeta.assets || []).map((asset) => {
      const assetPath = path.join(bundleDir, asset.path);
      const assetHash = fs.existsSync(assetPath) ? hashFileBase64(assetPath) : "";
      return {
        hash: assetHash,
        key: crypto.createHash("md5").update(asset.path).digest("hex"),
        contentType: getContentType(asset.ext),
        fileExtension: `.${asset.ext}`,
        url: `${serverUrl}/api/ota/assets/${apkVersion}/${otaVersion}/${asset.path}`,
      };
    });

    const manifest = {
      id: updateId,
      createdAt: createdAt,
      runtimeVersion: apkVersion,
      launchAsset: {
        hash: bundleHash,
        key: crypto.createHash("md5").update(platformMeta.bundle).digest("hex"),
        contentType: "application/javascript",
        url: `${serverUrl}/api/ota/assets/${apkVersion}/${otaVersion}/${platformMeta.bundle}`,
      },
      assets,
      metadata: {},
      extra: {
        expoClient: {
          name: "Sevak",
          slug: "Sevak",
          version: apkVersion,
          runtimeVersion: apkVersion,
          platforms: ["android"],
        },
      },
    };

    console.log(`[OTA] Serving update ${updateId} for ${platform}/${apkVersion}`);
    console.log("[OTA] Manifest:", JSON.stringify(manifest, null, 2));

    if (protocolVersion === "1") {
      return sendMultipartManifest(res, manifest);
    }

    res.setHeader("expo-protocol-version", "0");
    res.setHeader("expo-sfv-version", "0");
    res.setHeader("cache-control", "private, max-age=0");
    return res.json(manifest);
  } catch (err) {
    console.error("[OTA] manifest error:", err);
    return res.status(500).json({ error: err.message });
  }
};

/**
 * GET /api/ota/assets/:apkVersion/:otaVersion/*
 * Serves bundle and asset files.
 */
export const getAsset = (req, res) => {
  try {
    const { apkVersion, otaVersion } = req.params;
    const assetPath = req.params[0];
    const filePath = path.join(OTA_DIR, apkVersion, otaVersion, assetPath);

    console.log(`[OTA] Asset request: ${filePath}`);

    if (!fs.existsSync(filePath)) {
      console.error(`[OTA] Asset not found: ${filePath}`);
      return res.status(404).json({ error: "Asset not found" });
    }

    const stat = fs.statSync(filePath);
    const ext = path.extname(filePath).toLowerCase();

    res.setHeader("Content-Type", getContentType(ext.replace(".", "")));
    res.setHeader("Content-Length", stat.size);
    res.setHeader("Cache-Control", "public, max-age=31536000, immutable");

    fs.createReadStream(filePath).pipe(res);
  } catch (err) {
    console.error("[OTA] asset error:", err);
    res.status(500).json({ error: err.message });
  }
};

function getContentType(ext) {
  const map = {
    js: "application/javascript",
    hbc: "application/javascript",
    png: "image/png",
    jpg: "image/jpeg",
    jpeg: "image/jpeg",
    gif: "image/gif",
    svg: "image/svg+xml",
    ttf: "font/ttf",
    otf: "font/otf",
    woff: "font/woff",
    woff2: "font/woff2",
    json: "application/json",
  };
  return map[ext] || "application/octet-stream";
}

function sendNoUpdate(res, protocolVersion) {
  if (protocolVersion === "1") {
    const boundary = `ota-boundary-${Date.now()}`;
    res.setHeader("Content-Type", `multipart/mixed; boundary=${boundary}`);
    res.setHeader("expo-protocol-version", "1");
    res.setHeader("expo-sfv-version", "0");
    res.setHeader("cache-control", "private, max-age=0");
    const directive = JSON.stringify({ type: "noUpdateAvailable" });
    const body =
      `\r\n--${boundary}\r\n` +
      `Content-Disposition: inline; name="directive"\r\n` +
      `Content-Type: application/json\r\n\r\n` +
      `${directive}\r\n` +
      `--${boundary}--\r\n`;
    return res.send(body);
  }
  res.setHeader("expo-protocol-version", "0");
  return res.status(204).end();
}

function sendMultipartManifest(res, manifest) {
  const boundary = `ota-boundary-${Date.now()}`;
  res.setHeader("Content-Type", `multipart/mixed; boundary=${boundary}`);
  res.setHeader("expo-protocol-version", "1");
  res.setHeader("expo-sfv-version", "0");
  res.setHeader("cache-control", "private, max-age=0");

  const manifestJson = JSON.stringify(manifest);

  const body =
    `\r\n--${boundary}\r\n` +
    `Content-Disposition: inline; name="manifest"\r\n` +
    `Content-Type: application/json\r\n\r\n` +
    `${manifestJson}\r\n` +
    `--${boundary}--\r\n`;

  return res.send(body);
}
